import Navbar from './navbar'
import Footer from 'footer'

return (
    <div className={styles.container}>
      <Head>
        <title>Churros Camelô</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bienvenidos a <a href="https://nextjs.org">Churros Camelô!</a>
        </h1>
        <h2 className={styles.description}>
          Los más ricos de la Patagonia
        </h2>

        
      </main>

      <Footer props>

      </Footer>
      
    </div>
)